# Generated by Django 3.0.5 on 2020-04-16 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 4, 16, 14, 21, 56, 643106, tzinfo=utc)),
        ),
    ]
